### PR TITLE
Launcher icon

### LINKED ISSUE #27: Add a launcher icon

### PR DESCRIPTION
**Pull request by axross**
Closes #27.

preview (square)
preview (squircle)
preview (circle)
preview (teardrop)

### CODE REVIEW

**Comment by axross** [comment]
Added the command to generate launcher icons to codemagic.io.

**Comment by axross** [comment]
@ryotogashi Could you review the change?

**Comment by ryonryon** [comment]
@axross It doesn't link reviewer.

**Comment by axross** [comment]
Oh, sorry. I've just set!

**Review by ryonryon — APPROVED** [review]
image

**Comment by ryonryon** [comment]
thank you.

**Comment by axross** [comment]
Thanks!

**Pull request merged**
