### PR TITLE
Introduction / Tutorial

### PR DESCRIPTION
**Pull request by axross**
I implemented introduction for the first and the second ones at [this issue description](https://github.com/agnosticful/saraka-mobile/issues/117#issue-433070656).

### CODE REVIEW

**Comment by axross** [comment]
We're gonna come up with the details for descriptions

**Comment by axross** [comment]
@ryotogashi Can you review these changes?

**Review by ryonryon — APPROVED** [review]
image

**Comment by axross** [comment]
@ryotogashi ありがとうございました◎

**Pull request merged**
