### PR TITLE
Change transition to go to ReviewRoute

### PR DESCRIPTION
**Pull request by axross**
Change transition: "from left" to "from bottom"

### CODE REVIEW

**Comment by axross** [comment]
@ryotogashi Can you review these changes?

**Review by ryonryon — COMMENTED** [review]
image

**Comment by axross** [comment]
@ryotogashi What you did was a comment. I'm afraid that... can you approve it as a review instead?

**Review by ryonryon — APPROVED** [review]
@axross Sorry

**Comment by axross** [comment]
No worry! Thanks!

**Pull request merged**
