### PR TITLE
Fix flutter run failure

### PR DESCRIPTION
**Pull request by axross**
I tried to fix `flutter run` failure with several web articles.

- https://qiita.com/mkosuke/items/afa40c09078285034799
- https://github.com/flutter/flutter/issues/18494
- https://developer.android.com/ndk/guides/abis?hl=ja
- https://medium.com/flutterpub/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd

### CODE REVIEW

**Comment by axross** [comment]
@ryotogashi Can you try it and leave a review?

**Review by ryonryon — COMMENTED** [review]
@axross  Thanks! I could run with your solution. However, there are errors below.

Launching lib/main.dart on Pixel 3 in debug mode...
Initializing gradle...                                              0.9s
Resolving dependencies...                                          10.3s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
ERROR: [TAG] Failed to resolve variable '${junit.version}'              
ERROR: [TAG] Failed to resolve variable '${animal.sniffer.version}'     
Note: /Users/togashiryo/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.13+1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Users/togashiryo/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.13+1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Note: /Users/togashiryo/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-2.1.1+1/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Note: /Users/togashiryo/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.3.4/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.                      
ERROR: [TAG] Failed to resolve variable '${animal.sniffer.version}'     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        67.0s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         4.8s
I/chatty  ( 2610): uid=10240(app.axross.saraka) FirestoreWorker identical 2 lines
I/p.axross.sarak( 2610): The ClassLoaderContext is a special shared library.
V/NativeCrypto( 2610): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 284 native methods...
W/p.axross.sarak( 2610): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (light greylist, reflection)
I/ProviderInstaller( 2610): Installed default security provider GmsCore_OpenSSL
W/p.axross.sarak( 2610): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
W/p.axross.sarak( 2610): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
W/p.axross.sarak( 2610): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, linking)
W/p.axross.sarak( 2610): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, linking)
W/p.axross.sarak( 2610): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
W/p.axross.sarak( 2610): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (light greylist, reflection)
W/p.axross.sarak( 2610): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (light greylist, linking)
W/p.axross.sarak( 2610): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (light greylist, linking)
D/skia    ( 2610): --- Failed to create image decoder with message 'unimplemented'
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
I/flutter ( 2610): Expected backend version: 1                          
I/flutter ( 2610): Backend version: 1                                   
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
W/CrashlyticsCore( 2610): No minidump data found in directory /data/user/0/app.axross.saraka/files/.Fabric/com.crashlytics.sdk.android.crashlytics-ndk/native/1555219959718
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
D/skia    ( 2610): Program linking failed.                              
D/skia    ( 2610): Load program binary failed                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            3,274ms (!)                                                                                                                                                                     

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Pixel 3 is available at: http://127.0.0.1:56888/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

**Comment by axross** [comment]
@ryotogashi Did you do `flutter clean` ?

**Comment by axross** [comment]
Here it is the output on my laptop:

```
$ flutter run
Launching lib/main.dart on Pixel 3 in debug mode...
Initializing gradle...                                              1.3s
Resolving dependencies...                                           4.9s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: /Users/axross/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.13+1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/axross/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.13+1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/axross/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-2.1.1+1/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/axross/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.3.4/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        33.5s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         4.1s
I/chatty  (12089): uid=10299(app.axross.saraka) FirestoreWorker identical 1 line
I/p.axross.sarak(12089): The ClassLoaderContext is a special shared library.
V/NativeCrypto(12089): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 284 native methods...
W/p.axross.sarak(12089): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (light greylist, reflection)
I/ProviderInstaller(12089): Installed default security provider GmsCore_OpenSSL
W/p.axross.sarak(12089): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
W/p.axross.sarak(12089): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
W/p.axross.sarak(12089): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, linking)
W/p.axross.sarak(12089): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, linking)
W/p.axross.sarak(12089): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
W/p.axross.sarak(12089): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (light greylist, reflection)
W/p.axross.sarak(12089): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (light greylist, linking)
W/p.axross.sarak(12089): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (light greylist, linking)
D/skia    (12089): --- Failed to create image decoder with message 'unimplemented'
W/CrashlyticsCore(12089): No minidump data found in directory /data/user/0/app.axross.saraka/files/.Fabric/com.crashlytics.sdk.android.crashlytics-ndk/native/1555223996750
I/flutter (12089): Expected backend version: 1
I/flutter (12089): Backend version: 1
 2,693ms (!)                                                                                                                                                    🔥  To hot reload changes while running, press "r". To hot restart (and rebuild  state), press "R".                                                              An Observatory debugger and profiler on Pixel 3 is available at:
http://127.0.0.1:58315/
For a more detailed help message, press "h". To detach, press "d"; to quit,
press "q".
V/FA      (12089): Inactivity, disconnecting from the service
```

**Comment by ryonryon** [comment]
@axross I did ```flutter clean``` this time

log is this
```
Launching lib/main.dart on Pixel 3 in debug mode...
Initializing gradle...                                              0.9s
Resolving dependencies...                                           3.8s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: /Users/togashiryo/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.13+1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Users/togashiryo/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.13+1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Note: /Users/togashiryo/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-2.1.1+1/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Note: /Users/togashiryo/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.3.4/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.                      
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        34.7s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         3.8s
E/libc    (19286): Access denied finding property "vendor.gralloc.enable_ahardware_buffer"
W/RenderThread(19286): type=1400 audit(0.0:1002): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=19995 scontext=u:r:untrusted_app:s0:c240,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
D/libcrashlytics(19286): Initializing libcrashlytics version 2.0.5
D/libcrashlytics(19286): Initializing native crash handling successful.
I/CrashlyticsCore(19286): Initializing Crashlytics 2.6.7.30
D/NetworkSecurityConfig(19286): No Network Security Config specified, using platform default
W/DynamiteModule(19286): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(19286): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(19286): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/p.axross.sarak(19286): The ClassLoaderContext is a special shared library.
I/p.axross.sarak(19286): The ClassLoaderContext is a special shared library.
I/p.axross.sarak(19286): The ClassLoaderContext is a special shared library.
I/p.axross.sarak(19286): The ClassLoaderContext is a special shared library.
V/NativeCrypto(19286): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 284 native methods...
W/p.axross.sarak(19286): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (light greylist, reflection)
I/ProviderInstaller(19286): Installed default security provider GmsCore_OpenSSL
W/p.axross.sarak(19286): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
W/p.axross.sarak(19286): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
W/p.axross.sarak(19286): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, linking)
W/p.axross.sarak(19286): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, linking)
W/p.axross.sarak(19286): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
W/p.axross.sarak(19286): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (light greylist, reflection)
W/p.axross.sarak(19286): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (light greylist, linking)
W/p.axross.sarak(19286): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (light greylist, linking)
D/skia    (19286): --- Failed to create image decoder with message 'unimplemented'
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
I/flutter (19286): Expected backend version: 1                          
I/flutter (19286): Backend version: 1                                   
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
D/skia    (19286): Program linking failed.                              
D/skia    (19286): Load program binary failed                           
W/CrashlyticsCore(19286): No minidump data found in directory /data/user/0/app.axross.saraka/files/.Fabric/com.crashlytics.sdk.android.crashlytics-ndk/native/1555228129737
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      3,889ms (!)                                                                                                                                                                     

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Pixel 3 is available at: http://127.0.0.1:61750/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

```

**Comment by axross** [comment]
As it works well apart from occuring Skia's errors. I wanna merge this pull request and make that problem as a different issue.

@ryotogashi Can you leave an approved review?

**Review by ryonryon — APPROVED** [review]
OK!

**Comment by axross** [comment]
Thanks!

**Pull request merged**
